import 'package:flutter/material.dart';

abstract class Global {
  static const Color white = Colors.white38;
  static const Color boxColor = Colors.blueAccent;
  static const Color blue = Colors.blue;

  static const List ruang = [
    {
      'location': 'LABORATORIUM',
      'name': 'Ima Kusumawati, A.Md.AK',
      'title': 'LABORAN',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.03, -0.04],
      'tile': 16,
    },
    {
      'location': 'PENDAFTARAN',
      'name': 'Rahmat Setiyoko, A.Md',
      'title': 'STAF REKAM MEDIS',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.06, -0.03],
      'tile': 11,
    },
    {
      'location': 'R.IMUNISASI',
      'name': 'Dianita ND, A.Md.Keb',
      'title': 'BIDAN',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.0, -0.03],
      'tile': 11,
    },
    {
      'location': 'RAWAT INAP',
      'name': 'dr. Ana Adila',
      'title': 'DOKTER UMUM',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.07, 0.02],
      'tile': 10,
    },
    {
      'location': 'R.GIZI',
      'name': 'Aldhina Yusmarajanti, A.Md.Gz',
      'title': 'NUTRISIONIS',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.03, -0.07],
      'tile': 16,
    },
    {
      'location': 'R.VAKSIN',
      'name': 'Dianita ND, A.Md.Keb',
      'title': 'BIDAN',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.03, -0.05],
      'tile': 16,
    },
    {
      'location': 'UGD',
      'name': 'M. Anja Ardi, A.Md.Kep',
      'title': 'PERAWAT',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.03, -0.03],
      'tile': 12,
    },
    {
      'location': 'MTBS',
      'name': 'Herlina Ika M, A.Md.Keb',
      'title': 'BIDAN',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.023, -0.03],
      'tile': 12,
    },
    {
      'location': 'POLI GIGI',
      'name': 'drg. Fitri Nuraini',
      'title': 'DOKTER GIGI',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.05, 0.05],
      'tile': 12,
    },
    {
      'location': 'POLI UMUM',
      'name': 'dr. Lingga Sri Muninggar',
      'title': 'DOKTER UMUM',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.012, 0.05],
      'tile': 12,
    },
    {
      'location': 'APOTEK',
      'name': '-',
      'title': 'APOTEKER',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.077, 0.05],
      'tile': 11,
    },
    {
      'location': 'R.KIA/KB',
      'name': 'Asih Dwi L,S.Tr.Keb',
      'title': 'BIDAN',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.01, 0.05],
      'tile': 11,
    },
    {
      'location': 'RUANG RAPAT',
      'name': 'Meeting Room',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.01, -0.1],
      'tile': 13,
    },
    {
      'location': 'R.DOKTER',
      'name': 'DOKTER GIGI & UMUM',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.042, -0.06],
      'tile': 13,
    },
    {
      'location': 'R.KA.PUSKESMAS',
      'name': 'drg. Martin Widiastuti',
      'title': 'DOKTER GIGI',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.02, -0.03],
      'tile': 13,
    },
    {
      'location': 'R.ARSIP',
      'name': '-',
      'title': 'RUANG ARSIP',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.042, 0.08],
      'tile': 13,
    },
    {
      'location': 'R.KRENOVA',
      'name': '-',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.02, 0.04],
      'tile': 13,
    },
    {
      'location': 'R.ADMIN',
      'name': '-',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.042, 0.02],
      'tile': 13,
    },
    {
      'location': 'R.SERVER',
      'name': '-',
      'title': 'RUANG SERVER',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.02, 0.08],
      'tile': 13,
    },
    {
      'location': 'R.KA.TU',
      'name': '-',
      'title': 'RUANG SERVER',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.018, 0.08],
      'tile': 13,
    },
    {
      'location': 'TPS & IPAL',
      'name': 'TPS & IPAL',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.05, -0.04],
      'tile': 14,
    },
    {
      'location': 'GD BELAKANG LT.1',
      'name': 'MUSHOLA,SARPRAS,POLI TB',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.085, -0.08],
      'tile': 20,
    },
    {
      'location': 'GD BELAKANG LT.2',
      'name': 'RUANG LAUNDRY',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.04, -0.08],
      'tile': 20,
    },
    {
      'location': 'RUMAH DINAS',
      'name': 'Rumah Dinas',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.09, -0.09],
      'tile': 21,
    },
    {
      'location': 'TEMPAT PARKIR',
      'name': 'Parkir Ambulance & Kendaraan',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [0.03, 0.03],
      'tile': 17,
    },
    {
      'location': 'PINTU MASUK',
      'name': 'Pintu Utama',
      'title': '-',
      'photo': 'assets/person/person1.jpg',
      'locationphoto': 'assets/person/person1.jpg',
      'status': true,
      'position': [-0.083, -0.05],
      'tile': 12,
    },
  ];
}
