abstract class Global {
  //position [x,y] / position [left,top]
  // [0] = x, [1] = y
  static const List ruang = [
    {
      'location': 'LABORATORIUM',
      'name': 'Ima Kusumawati, A.Md.AK',
      'title': 'LABORAN',
      'photoPerson': "assets/person/LABORATORIUM.jpg",
      'photoLocation': "assets/location/LABORATORIUM.jpg",
      'position': [205.0, 538.0],
      'jadwalPelayanan': "SETIAP HARI",
      'pelayanan': [
        "Hematologi",
        "Darah rutin",
        "Haemoglobin",
        "Cloting Time (CT)",
        "Bleeding Time (BT)",
        "Hematokrit ",
        "Kimia Klinik",
        "Gula darah",
        "Cholesterol",
        "Trigliserid",
        "Asam urat",
        "SGOT/AST",
        "SGPT/ALT",
        "Imunoserologi",
        "Golongan darah",
        "Widal",
        "HBsAg",
        "Syphilis",
        "Antigen HIV ",
        "Antigen Covid",
        "PPTest",
        "Parasitologi",
        "Malaria",
        "Feses rutin",
        "Bakteriologi",
        "BTA",
        "Urinalisa",
        "Urin rutin",
        "Urin lengkap",
        "Protein urin",
        "Reduksi urin",
        "Sedimen urin",
      ]
    },
    {
      'location': 'RAWAT INAP',
      'name': 'dr. Ana Adila',
      'title': 'DOKTER UMUM',
      'photoLocation': "assets/location/RAWAT INAP.jpg",
      'position': [132.0, 436.0],
      'jadwalPelayanan': "SETIAP HARI",
      'pelayanan': [
        "Rujukan",
        "Partus",
        "Umum",
      ]
    },
    {
      'location': 'PENDAFTARAN',
      'name': 'Rahmat Setiyoko, A.Md',
      'title': 'STAF REKAM MEDIS',
      'photoPerson': "assets/person/PENDAFTARAN.jpg",
      'photoLocation': "assets/location/PENDAFTARAN.jpg",
      'position': [285.0, 390.0],
    },
    {
      'location': 'R.IMUNISASI',
      'name': 'Dianita ND, A.Md.Keb',
      'title': 'BIDAN',
      'photoPerson': null,
      'photoLocation': "assets/location/R.IMUNISASI.jpg",
      'position': [231.0, 390.03],
      'jadwalPelayanan': "informasi dapat dilihat di ig : @pkm_kaliangkrik",
      'pelayanan': [
        '''Jadwal: kamis legi
      Imunisasi rutin
        BCG, Campak ''',
        '''Jadwal : setiap kamis
            Polio, Penta''',
        "Jadwal Menyesuaikan untuk Imunisasi covid"
      ]
    },
    {
      'location': 'R.GIZI',
      'name': 'Aldhina Yusmarajanti, A.Md.Gz',
      'title': 'NUTRISIONIS',
      'photoPerson': "assets/person/R.GIZI.jpg",
      'photoLocation': "assets/location/R.GIZI.jpg",
      'position': [204.0, 510.0],
    },
    {
      'location': 'R.VAKSIN',
      'name': 'Dianita ND, A.Md.Keb',
      'title': 'BIDAN',
      'photoPerson': "assets/person/R.VAKSIN.jpg",
      'photoLocation': "assets/location/R.VAKSIN.jpg",
      'position': [258.0, 522.0],
    },
    {
      'location': 'UGD',
      'name': 'M. Anja Ardi, A.Md.Kep',
      'title': 'PERAWAT',
      'photoPerson': "assets/person/UGD.jpg",
      'photoLocation': "assets/location/UGD.jpg",
      'position': [365.0, 390.0],
    },
    {
      'location': 'MTBS',
      'name': 'Herlina Ika M, A.Md.Keb',
      'title': 'BIDAN',
      'photoPerson': "assets/person/MTBS.jpg",
      'photoLocation': "assets/location/MTBS.jpg",
      'position': [413.0, 390.0],
      'jadwalPelayanan': "SETIAP HARI",
      'pelayanan': [
        "Pelayanan bayi dan balita sakit",
      ]
    },
    {
      'location': 'POLI GIGI',
      'name': 'drg. Fitri Nuraini',
      'title': 'DOKTER GIGI',
      'photoPerson': "assets/person/POLI GIGI.jpg",
      'photoLocation': "assets/location/POLI GIGI.jpg",
      'position': [440.0, 390.0],
      'jadwalPelayanan': "Setiap Hari",
      'pelayanan': [
        "Tambal gigi",
        "Cabut gigi dewasa dan anak",
        "Premedikasi",
        "Konsultasi",
        "Perawatan akar",
        "Pemeriksaan ibu hamil",
        "Scalling",
      ]
    },
    {
      'location': 'POLI UMUM',
      'name': 'dr. Lingga Sri Muninggar',
      'title': 'DOKTER UMUM',
      'photoPerson': "assets/person/POLI UMUM.jpg",
      'photoLocation': "assets/location/POLI UMUM.jpg",
      'position': [380.0, 455.0],
      'jadwalPelayanan': "Setiap Hari",
      'pelayanan': [
        "Pelayanan pengobatan umum",
        "Pembuatan surat keterangan sehat",
        "Pembuatan surat bebas buta warna",
        "Pelayanan rujukan (dengan indikasi)",
        "Visum",
        "Tindakan",
        "Prolanis (Program pengelolaan penyakit kronis) & PRB (Program Rujuk Balik)"
      ]
    },
    {
      'location': 'APOTEK',
      'name': '-',
      'title': 'APOTEKER',
      'photoPerson': "assets/person/APOTEK.jpg",
      'position': [300.0, 455.0],
    },
    {
      'location': 'R.KIA KB',
      'name': 'Asih Dwi L,S.Tr.Keb',
      'photoPerson': "assets/person/R.KIA KB.jpg",
      'photoLocation': "assets/location/R.KIA KB.jpg",
      'title': 'BIDAN',
      'position': [225.0, 455.0],
      'jadwalPelayanan': "Senin: implant, Rabu: IUD, IVA",
      'pelayanan': [
        "Pemeriksaan kehamilan, nifas,BBL",
        "Pelayanan KB",
        "Pemeriksaan IVA",
        "Konseling",
        "Pelayanan calon pengantin",
      ]
    },
    {
      'location': 'RUANG RAPAT',
      'name': 'Meeting Room',
      'title': '-',
      'photoLocation': "assets/location/RUANG RAPAT.jpg",
      'position': [565.0, 330.0],
    },
    {
      'location': 'R.DOKTER',
      'name': 'DOKTER GIGI & UMUM',
      'title': '-',
      'photoLocation': "assets/location/R.DOKTER.jpg",
      'position': [590.0, 363.0],
    },
    {
      'location': 'R.KA.PUSKESMAS',
      'name': 'drg. Martin Widiastuti',
      'title': 'DOKTER GIGI',
      'photoPerson': "assets/person/R.KA.PUSKESMAS.jpg",
      'photoLocation': "assets/location/R.KA.PUSKESMAS.jpg",
      'position': [533.0, 388.0],
    },
    {
      'location': 'R.ARSIP',
      'name': '-',
      'title': 'RUANG ARSIP',
      'photoLocation': "assets/location/R.ARSIP.jpg",
      'position': [593.0, 483.0],
    },
    {
      'location': 'R.KRENOVA',
      'name': '-',
      'title': '-',
      'photoLocation': "assets/location/R.KRENOVA.jpg",
      'position': [532.0, 455.0],
    },
    {
      'location': 'R.ADMIN',
      'name': '-',
      'title': '-',
      'photoLocation': "assets/location/R.ADMIN.jpg",
      'position': [590.0, 436.0],
    },
    {
      'location': 'R.SERVER',
      'name': '-',
      'title': 'RUANG SERVER',
      'photoLocation': "assets/location/R.SERVER.jpg",
      'position': [542.0, 483.0],
    },
    {
      'location': 'R.KA.TU',
      'name': '-',
      'title': 'R.KA.TU',
      'photoPerson': "assets/person/R.KA.TU.jpg",
      'photoLocation': "assets/location/R.KA.TU.jpg",
      'position': [569.0, 483.0],
    },
    {
      'location': 'TPS & IPAL',
      'name': 'TPS & IPAL',
      'title': '-',
      'photoLocation': "assets/location/TPS & IPAL.jpg",
      'position': [658.0, 348.0],
    },
    {
      'location': 'GD BELAKANG LT.1',
      'name': 'MUSHOLA,SARPRAS,POLI TB',
      'title': '-',
      'photoLocation': "assets/location/GD BELAKANG LT.1.jpg",
      'position': [147.0, 670.0],
    },
    {
      'location': 'GD BELAKANG LT.2',
      'name': 'RUANG LAUNDRY',
      'title': '-',
      'photoLocation': "assets/location/GD BELAKANG LT.2.jpg",
      'position': [115.0, 681.0],
    },
    {
      'location': 'RUMAH DINAS',
      'name': 'Rumah Dinas',
      'title': '-',
      'photoLocation': "assets/location/RUMAH DINAS.jpg",
      'position': [323.0, 657.0],
    },
    {
      'location': 'TEMPAT PARKIR',
      'name': 'Parkir Ambulance & Kendaraan',
      'title': '-',
      'photoLocation': "assets/location/TEMPAT PARKIR.jpg",
      'position': [421.0, 602.0],
    },
    {
      'location': 'PINTU MASUK',
      'name': 'Pintu Utama',
      'title': '-',
      'photoLocation': "assets/location/PINTU MASUK.jpg",
      'position': [320.0, 350.0],
    },
  ];
}
